### PR TITLE
Converting pyqt4 to qtpy

### PR DESCRIPTION
**Pull request by wdeacon**
Wrote a program to convert python files from using PyQt4 to PyQt5 syntax. The Imports are all redirected to go through nplab.utils.gui to allow easier modification down the line and the imports are actually coming from qtpy so that they can run on any qt platform. N.B. the program looks through all sub folders for python files (potentially a bad idea). 

Please create backups before running the program on any of your own files, I will not be held responsible for any mistakes!!!

The program has been run on nplab.

The program used is nplab.utils.PyQtToQtpy.

### CODE REVIEW

**Comment by rwb27** [comment]
This looks nice to me - I can't test it right now but will do so when I have some hardware in front of me, or at least a Windoze box.  The thing that always stumped my attempts to be properly cross-platform was the pic module, but it seems that qtpy has a good work-around for that (they reimplement an equivalent function based on some underlying Qt stuff) so the major stumbling block is fixed :)

**Comment by wdeacon** [comment]
No hurry,
So generally it is fine with uic if you use uic.loadUI however the uic.loadUitype appears to have disappeared in Qt5. So I have changed some of the imports around. 

The other thing that may need some attention is that the QtCore.pyqtsignal is not in qtpy.
 I tried changing them to QtCore.pyqtboundsignal as I think that should be identical however it caused the code to crash so I have changed them to QtCore.Signal which appears fine for everything I have tested so far (camera and spectrometer) but I believe you lose functionality?

**Comment by rwb27** [comment]
Cool.  I have favoured `loadUI` over `loadUiType` because the former delays the (slow) UI compilation until it's needed, meaning that code that doesn't use a given UI isn't slowed down by recompiling it pointlessly.  As a rule, I've tried to arrange things so as to avoid slowing down code that doesn't need features like the GUI.  That's why you'll find a few imports of GUI stuff inside if statements, etc. so they're only done if needed.

As for signals, I'm pretty sure `pyQtSignal` became `QtCore.Signal` in the 4->5 migration, so I think that's the right thing to do.  There are some subtle changes as regards overloaded signals (i.e. ones with different possible combinations of arguments) but I'm hoping they won't affect us.

What's your issue with `fileinput`?  It looks like it should be pretty uncontroversial (just a fairly thin wrapper dealing with some argument handling)...

**Comment by wdeacon** [comment]
Yep, I agree about the qtgui, I wasn't really sure why it was there but I thought I had better leave it just in case. 

My problem with fileinput is that when running in inline mode it overwrites standard output command so that if you use print statements any where they write to the file instead of the console. Which is a massive pain in the arse for debugging. So if I was going to do it again I would just use standard open file write to temporary and overwrite the old one.

In terms of the slowing of the files due to loading the ui file unnecessary, I placed the ui file loading within the pythonUI class it self so I don't think that should be a problem (not very often at least). Only annoying thing is this conversion currently has to be done manually.

**Comment by wdeacon** [comment]
Cheers for having a look, I will Merge the request once I've asked anyone if they are using the loadUitype command in a Monday meeting so that I can show them how to fix it.

**Pull request merged**
